version: "3"

services:
    calc_app:
        build: ./
        ports:
            - "8855:8855"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://127.0.0.1:8855/up.cfm"]
          interval: 90s
          timeout: 5s
          retries: 3
          start_period: 30s


        