# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cfcompile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cfcompile
      uses: foundeo/cfml-compiler-action@master
      with:
        cfengine: lucee@5.2.9.31
  
  fixinator:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Fixinator Security Scan 
      uses: foundeo/fixinator-github-action@master
      with:
        fixinator_api_key: ${{ secrets.FIXINATOR_API_KEY }}
  
  
  cflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run CFLint	    
      uses: docker://foundeo/cfml-ci-tools:latest
      with:
        entrypoint: /opt/box/box
        args: cflint reportLevel=ERROR
        
  codechecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run CodeChecker	    
      uses: docker://foundeo/cfml-ci-tools:latest
      with:
        entrypoint: /opt/box/box
        args: codechecker run --verbose

  