name: Compile ColdFusion

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  cfcompile:
    runs-on: ubuntu-latest
    container:
      image: adobecoldfusion/coldfusion2021:2021.0.13
    env:
      acceptEULA: YES
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs the cfcompile command inside the docker container
      - name: Compile CFML
        run: /opt/coldfusion/cfusion/bin/cfcompile.sh -cfruntimeuser root -webroot $GITHUB_WORKSPACE -dir $GITHUB_WORKSPACE
          
          
