name: Compile Lucee

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  cfcompile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cfcompile
      uses: foundeo/cfml-compiler-action@master
      with:
        cfengine: lucee@5.4.3.2