# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      fixinator_confidence:
        description: 'The confidence level for fixinator to run at, options are `high`, `medium`, or `low`'
        default: 'high'
        required: true

jobs:
  fixinator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundeo/cfml-ci-tools/cfml-ci-tools:v1.0.15
    
    steps:
    - uses: actions/checkout@v4
    - name: Banner
      run: ls
    - name: Run Fixinator
      run: box fixinator confidence=${{ github.event.inputs.fixinator_confidence }}
      env:
        FIXINATOR_API_KEY: ${{ secrets.FIXINATOR_API_KEY }}
    
