# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      fixinator_confidence:
        description: 'The confidence level for fixinator to run at, optiosn are `high`, `medium`, or `low`'
        default: 'high'
        required: true

jobs:
  fixinator:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundeo/cfml-ci-tools:latest
    steps:
    - name: Banner
      run: echo "Running Fixinator with confidence=${{ github.event.inputs.fixinator_confidence }}"
    - name: Run Fixinator
      run: box fixinator confidence=${{ github.event.inputs.fixinator_confidence }}
